#include <iostream>
#include <string>

using namespace std;

class RecursiveDescentParser {
private:
    string input;
        int index;

            
                bool match(char expected) {
                        if (index < input.length() && input[index] == expected) {
                                    index++;
                                                return true;
                                                        }
                                                                return false;
                                                                    }

                                                                        
                                                                            bool S() {
                                                                                    if (match('a')) {
                                                                                                return true;
                                                                                                        } else if (match('(')) {
                                                                                                                    if (L() && match(')')) {
                                                                                                                                    return true;
                                                                                                                                                }
                                                                                                                                                        }
                                                                                                                                                                return false;
                                                                                                                                                                    }

                                                                                                                                                                       
                                                                                                                                                                            bool L() {
                                                                                                                                                                                    if (S()) {
                                                                                                                                                                                                return L_prime();
                                                                                                                                                                                                        }
                                                                                                                                                                                                                return false;
                                                                                                                                                                                                                    }

                                                                                                                                                                                                                        
                                                                                                                                                                                                                            bool L_prime() {
                                                                                                                                                                                                                                    if (match(',')) {
                                                                                                                                                                                                                                                if (S()) {
                                                                                                                                                                                                                                                                return L_prime();
                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                        return false;
                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                        return true; 
                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                            public:
                                                                                                                                                                                                                                                                                                                RecursiveDescentParser(string str) {
                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                input = "";
                                                                                                                                                                                                                                                                                                                                        for (char c : str) {
                                                                                                                                                                                                                                                                                                                                                    if (c != ' ') input += c;
                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                    index = 0;
                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                bool isValid() {
                                                                                                                                                                                                                                                                                                                                                                                        return S() && index == input.length();
                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                                                                                                                                                            int main() {
                                                                                                                                                                                                                                                                                                                                                                                                string test_cases[] = {"a", "(a)", "(a,a)", "(a,(a,a),a)", "(a,a),(a,a)", "a)", "(a a)", "(a,a a)", "(a,a),a"};
                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                        for (const string& test : test_cases) {
                                                                                                                                                                                                                                                                                                                                                                                                                RecursiveDescentParser parser(test);
                                                                                                                                                                                                                                                                                                                                                                                                                        cout << "Input: " << test << " -> Output: " << (parser.isValid() ? "Valid string" : "Invalid string") << endl;
                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                return 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                